### ISSUE TITLE
Connecting to many IRCs 

### ISSUE THREAD

**Issue by rudolphyo** [Pytwitcher/pytwitcherapi#19]
Hello @storax!

I noticed that this repository is not developed anymore, but only your API lets me easily access stream chats on twitch for my personal NLP project.

I`d like to know why I can`t authorize to chat more than once. Is there some default socket that should differ for each authorization?

Thank you!

**Comment by storax** [comment]
Are you trying to authorize multiple times? It uses a specific url (and port) that is configured for the specific client id.
When you register a client with twitch, you have to specify the redirect URL, which pytwitcher API will listen for. It has to be the same URL that is configured in constants.py.

Roughly what happens is: pytwitcherapi spins up a login server under localhost:42420 and asks you to open the webbrowser, which sends an authorization request to twitch. On success, twitch redirects the browser to localhost:42420 and the login server gets the token from that request.

If you start another login server before shutting the old one down, it will say that the address is in use.
This is partly my fault because pytwitcherapi never kills the login server.
There are two options. One is to manually shutdown the login server after authorization and authorize each session one by one:
```
import pytwitcherapi
import sys
import threading
import logging
import webbrowser

log = logging.getLogger("chat")
logging.basicConfig(level=logging.INFO)

if sys.version_info[0] == 3:
    raw_input = input

def authorize(session):
    session.start_login_server()
    url = session.get_auth_url()
    webbrowser.open(url)
    raw_input("Please authorize Pytwitcher in the browser then press ENTER!")
    assert session.authorized, "Authorization failed! Did the user allow it?"


session = pytwitcherapi.TwitchSession()
authorize(session)
session.shutdown_login_server()
session2 = pytwitcherapi.TwitchSession()
authorize(session2)
session2.shutdown_login_server()
```
This would also work if you fire up multiple processes. Just make sure to let one process authorize at a time.

You can also use a single session for multiple chats. I just tested it with the code from the examples.
Here is my hacked together test:

```
import pytwitcherapi
import sys
import threading
import logging
import webbrowser

log = logging.getLogger("chat")
logging.basicConfig(level=logging.INFO)

if sys.version_info[0] == 3:
    raw_input = input

def create_client(session, channelname):
    channel = session.get_channel(channelname)
    return IRCClient(session, channel)


def authorize(session):
    session.start_login_server()
    url = session.get_auth_url()
    webbrowser.open(url)
    raw_input("Please authorize Pytwitcher in the browser then press ENTER!")
    assert session.authorized, "Authorization failed! Did the user allow it?"


class IRCClient(pytwitcherapi.IRCClient):
    """This client will print out private and public messages"""
    def on_pubmsg(self, connection, event):
        super(IRCClient, self).on_pubmsg(connection, event)
        message = self.messages.get()
        log.info('%s:%s: %s' % (self.channel, message.source.nickname, message.text))
    def on_privmsg(self, connection, event):
        super(IRCClient, self).on_pubmsg(connection, event)
        message = self.messages.get()
        log.info('%s:%s: %s' % (self.channel, message.source.nickname, message.text))

session = pytwitcherapi.TwitchSession()
authorize(session)
clients = []
threads = []
for channel in ["imaqtpie", "Trick2G", "Mathil1", "AnnieBot"]:
    client = client = create_client(session, channel)
    t = threading.Thread(target=client.process_forever)
    clients.append(client)
    threads.append(t)
    t.start()

raw_input("Type ENTER to stop")
for c, t in zip(clients, threads):
    c.shutdown()
    t.join()

```

I hope this helps. Good luck with your NLP project.

**Comment by rudolphyo** [comment]
Brilliant! Sure this helps.
Thank you a lot, David!

Best regards!
